### ISSUE TITLE
Initial version of the component

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-time-picker-flow#1]
### Acceptance Criteria
- Demos of component
- Make initial API where the type is `HasValue<LocalTime>`
  - The I18N & Locale API can be left for #2

**Comment by ZheSun88** [comment]
the current webcomponent version `1.0.0-alpha1` haven't been released to bower yet, (so the generator cannot be used at the moment), the component team is going to do a beta release soon, together with the bower semver fix also(for the webjar deployment).
