### ISSUE TITLE
Can not be used with Vaadin 10.0.9

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-time-picker-flow#10]
When I add the dependency as below, I take this error from IDE -> (**Missing artifact com.vaadin:vaadin-time-picker-flow:jar:1.0.0**)

`<dependency>
		    <groupId>com.vaadin</groupId>
		    <artifactId>vaadin-time-picker-flow</artifactId>
		    <version>1.0.0</version>
</dependency>
`

**Comment by pleku** [comment]
TimePicker 1.0 requires Flow 1.2 or newer to work, so you should update to Vaadin 12. It will be part of Vaadin 13.

We have not promised support for Vaadin 10 for time picker Java integration. I think it could be done if the flow and web component versions would be downgraded, but we don't have that in our plans.

The code is available, so anyone can do it themself and release it in vaadin.com/directory

**Comment by ugurdoksan** [comment]
Does Vaadin 12 contains all of the features and advantages of Vaadin 10. If it is so, I'll  update to Vaadin12.

Is there any dis-advantage of Vaadin 12 over the Vaadin 10?

**Comment by pleku** [comment]
But now that I read your full description, I think the error indicates that there is something else wrong. I can't find the artifact from anywhere in the interwebs, so something is really wrong here. 

Sorry for the bad out-of-the-box message.

**Comment by pleku** [comment]
V12 is better than V10 in many ways, please see details from https://vaadin.com/releases/vaadin-12 and https://github.com/vaadin/platform/releases/tag/12.0.0

The biggest difference is that V12 is lot LTS, but there are no plans for breaking changes between V10 and the next LTS so you should be able to just bump the version. There might be trivial API improvements, which you can read about in the release notes.

**Comment by pleku** [comment]
The artifact was missing from maven central / sonatype, but is there now. Closing
