### ISSUE TITLE
NPE if no locale is selected in component demo

### ISSUE THREAD

**Issue by paulroemer** [vaadin/vaadin-time-picker-flow#17]
Steps to reproduce:
1. https://vaadin.com/components/vaadin-time-picker/java-examples
2. Use the 'x' to delete the selected locale in "Localized Time Picker" demo

=> page will reload caused by the NPE

```
Locale must not be null.
  com.vaadin.flow.component.timepicker.demo.TimePickerView.lambda$createLocalizedTimePicker$ea26d33e$1(TimePickerView.java:69)
```

Used version from V13 beta1

**Comment by pleku** [comment]
Reopened, see comment https://github.com/vaadin/vaadin-time-picker-flow/pull/18#issuecomment-463652131

**Comment by fluorumlabs** [comment]
If the demo still needs workaround (see https://github.com/vaadin/vaadin-time-picker-flow/pull/18#issuecomment-463923528), why this issue is closed?
