### ISSUE TITLE
TimePicker in Grid causes TypeError

### ISSUE THREAD

**Issue by firestormdong** [vaadin/vaadin-time-picker-flow#22]
When I put TimePicker in a Grid component column, I will get a TypeError on the page, though the component itself is still working.

I used Vaadin 12.0.5 and vaadin-time-picker-flow-1.1.0

My code:
`
        Grid<LocalTime> grid = new Grid<>();
        grid.addComponentColumn(TimePicker::new).setHeader("Time");
        grid.setItems(
                LocalTime.of(0, 0),
                LocalTime.of(1, 0),
                LocalTime.of(2, 0)
        );
`
Screenshot in Firefox:
![image](https://user-images.githubusercontent.com/20729067/53198579-92de7400-35d1-11e9-980a-91d89269bb1a.png)

**Comment by ZheSun88** [comment]
Tested with Vaadin 12.0.7(the lastest release), the bug is still reproducible. 
It affects all other browsers : Chrome and Edge

**Comment by schaerl** [comment]
There is also a related issue (I guess, it's also a shadowRoot==null problem) when using a time picker as an editorComponent. Here is my code.

```java
import java.time.LocalTime;

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.timepicker.TimePicker;
import com.vaadin.flow.router.Route;

@Route("example")
public class ExampleView extends Grid<ExampleView.ExampleData> {

    public ExampleView() {
        super(ExampleData.class, true);
        setItems(new ExampleData(LocalTime.now()), new ExampleData(LocalTime.now()));
        TimePicker timePicker = new TimePicker();
        getEditor().getBinder().forField(timePicker).bind("time");
        getColumnByKey("time").setEditorComponent(timePicker);
        addItemDoubleClickListener(event -> getEditor().editItem(event.getItem()));
    }

    public static class ExampleData {
        LocalTime time;

        public ExampleData(LocalTime time) {
            this.time = time;
        }

        public LocalTime getTime() {
            return time;
        }

        public void setTime(LocalTime time) {
            this.time = time;
        }
    }
}
```
Opening the editor via double-click produces the following errors:
![image](https://user-images.githubusercontent.com/12117159/54617014-ddcc9980-4a60-11e9-8480-5c0f609148af.png)
![image](https://user-images.githubusercontent.com/12117159/54617074-f0df6980-4a60-11e9-9d77-71bf02acc8d4.png)

the `null` from which is read is `this.shadowRoot` as implied above

EDIT: By the way, this only happens on the first opening of the editor. Subsequent openings don't produce an error anymore, neither in the GUI nor in the DevTools. Also, the functionality does not seem to be affected, as saving the new value even works on the first opening

**Comment by brp-oskar** [comment]
We have the same issue but not within the Grid. We have a form where the TimePicker is "controlled" by a Binder. `setLocale` function in `timepickerConnector.js` is called before any web component in the form has been "initialized" and therefore `this.__inputElement` will throw a NPE.

We are using version `1.1.1` och `vaadin:vaadin-time-picker` with Vaadin 13.

**Comment by bsutton** [comment]
This is still an issue with 13.0.4

**Comment by barracus84** [comment]
Still in 13.0.7

**Comment by barracus84** [comment]
Still in 13.0.11

**Comment by JohannesLaidler** [comment]
Still in 14.0.5

**Comment by WoozyG** [comment]
While I have proposed a workaround that properly initializes while avoiding the client side errors, the real solution is to redo the underlying Polymer component to use browser-supported ECMA-402 features, such as [DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat), and store the locale as an attribute rather than replacing the formatting function when the locale changes.

**Comment by alvarezguille** [comment]
Time-boxed to 0.5 day to verify and check PR
