### ISSUE TITLE
setMin and setMax do nothing

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-time-picker-flow#27]
`vaadin.version 13.0.1`
Tested on Windows 10,  Chrome

Setting the `min` and `max` values is not working. I'd assume for example the following code:
```
        TimePicker timePicker = new TimePicker();
        timePicker.setMin("10:00");
        timePicker.setValue(LocalTime.NOON);
```
would create a time picker where I can't pick a time earlier than 10 AM, but it doesn't seem to do anything.

Same behavior can also be seen at https://vaadin.com/components/vaadin-time-picker/java-examples

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-time-picker #101](https://github.com/vaadin/vaadin-time-picker/issues/101) via [**ZenHub**](https://www.zenhub.com/)
