### ISSUE TITLE
NPE in setValue method

### ISSUE THREAD

**Issue by kasprzakpawel** [vaadin/vaadin-time-picker-flow#32]
The TimePicker flow component throws an NullPointerException when call setValue method (no NPE protection while call truncatedTo() at LocalTime value).

**Comment by ZheSun88** [comment]
Hi, thanks for reporting this. We have realized this bug and have already pushed a fix (#31 ) into the component. You will get the fixed version in `vaadin-time-picker-flow` 1.1.2

issue closed.
