### ISSUE TITLE
Setting a null value causes NPE

### ISSUE THREAD

**Issue by rrighi** [vaadin/vaadin-time-picker-flow#35]
Code to reproduce the error:
```
TimePicker tp = new TimePicker();
tp.setValue(null);
```
Exception:
```
java.lang.NullPointerException
	at com.vaadin.flow.component.timepicker.TimePicker.setValue(TimePicker.java:126)
```
I think the problem is here:
https://github.com/vaadin/vaadin-time-picker-flow/blob/1.1.1/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java#L126
Should ensure value is not `null` before invoking `value.truncatedTo(ChronoUnit.MILLIS)`.

**Comment by ZheSun88** [comment]
Hi @rrighi 

thanks for reporting this. And we have realized this bug and have already fixed it by [commit](https://github.com/vaadin/vaadin-time-picker-flow/pull/31). The fixes will shipped with next release, 1.1.2. 

issue closed.
