### ISSUE TITLE
min and max type is string (not LocalTime)

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-time-picker-flow#55]
<img width="746" alt="Screenshot 2019-09-02 at 16 27 00 " src="https://user-images.githubusercontent.com/1478052/64117839-e0b50f80-cd9e-11e9-8bff-61ed2144cd50.png">

**Comment by Haprog** [comment]
Related: https://vaadin.com/forum/thread/17821234/timepicker-setmin-vs-datepicker-setmin

**Comment by pleku** [comment]
Absolutely agree, it makes no sense as a String for Java side. The contribution should have not passed review.

**Comment by tulioag** [comment]
Fixed by #57
